### ISSUE TITLE
IndexError in runpf.py, line 212

### ISSUE THREAD

**Issue by Learwzr** [rwl/PYPOWER#70]
I meet an error when using runpf (enforce q limit):

Traceback (most recent call last):
  File "/data2/wzr/opf/data/generate_data.py", line 31, in <module>
    results, success = runpf(ppc, opt)
  File "/data2/wzr/anaconda3/envs/opf/lib/python3.7/site-packages/pypower/runpf.py", line 212, in runpf
    (bus[gen[:, GEN_BUS], BUS_TYPE] == PV | 
IndexError: arrays used as indices must be of integer (or boolean) type

Maybe the gen[:, GEN_BUS]  is not integer type.

please help!

**Comment by Bengt** [comment]
If I remember correctly, this is caused by an incompatible version please double check that you installed the correct library versions.
